/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unirb.gestao.jframe;

import br.unirb.gestao.dao.ColaboradorDao;
import br.unirb.modelo.Colaborador;
import br.unirb.gestao.views.CadastroAgenda;
import br.unirb.gestao.views.CadastroColaborador;
import br.unirb.gestao.views.CadastroDeEquipe;
import br.unirb.gestao.views.ListagemAgenda;
import br.unirb.gestao.views.ListagemColaborador;
import br.unirb.gestao.views.ListagemEquipe;
import br.unirb.gestao.views.TelaLogin;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class sistemagestajFrame extends javax.swing.JFrame {

    private TelaLogin tela = new TelaLogin();
    private ColaboradorDao col = new ColaboradorDao();
    private Colaborador c = new Colaborador();
    public String tipo= "";
    
   
    
    /**
     * Creates new form SisLojFrame
     */
    public sistemagestajFrame() throws SQLException {
        initComponents();

        
        painelPrincipal.add(tela, "telaPadrao");

        //Chamar a tela padrão aqui
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "telaPadrao");
        
        this.setExtendedState(MAXIMIZED_BOTH);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        barraDeMenu = new javax.swing.JMenuBar();
        menColaborador = new javax.swing.JMenu();
        menCadastrarCliente = new javax.swing.JMenuItem();
        menListarCliente = new javax.swing.JMenuItem();
        menAgenda = new javax.swing.JMenu();
        menCadastrarProduto = new javax.swing.JMenuItem();
        menListarProduto = new javax.swing.JMenuItem();
        menEquipe = new javax.swing.JMenu();
        menCadastrarEquipe = new javax.swing.JMenuItem();
        menListarEquipes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para gestão de loja");
        setSize(new java.awt.Dimension(800, 500));

        painelPrincipal.setLayout(new java.awt.CardLayout());

        menColaborador.setText("Colaborador");
        menColaborador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menColaboradorMouseClicked(evt);
            }
        });
        menColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menColaboradorActionPerformed(evt);
            }
        });

        menCadastrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        menCadastrarCliente.setText("Cadastrar colaborador");
        menCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastrarClienteActionPerformed(evt);
            }
        });
        menColaborador.add(menCadastrarCliente);

        menListarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        menListarCliente.setText("Listar colaboradores");
        menListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListarClienteActionPerformed(evt);
            }
        });
        menColaborador.add(menListarCliente);

        barraDeMenu.add(menColaborador);

        menAgenda.setText("Agenda");
        menAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menAgendaMouseClicked(evt);
            }
        });

        menCadastrarProduto.setText("Consultar agenda");
        menCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastrarProdutoActionPerformed(evt);
            }
        });
        menAgenda.add(menCadastrarProduto);

        menListarProduto.setText("Adicionar Tarefa");
        menListarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListarProdutoActionPerformed(evt);
            }
        });
        menAgenda.add(menListarProduto);

        barraDeMenu.add(menAgenda);

        menEquipe.setText("Equipe");
        menEquipe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menEquipeMouseClicked(evt);
            }
        });

        menCadastrarEquipe.setText("Cadastrar equipe");
        menCadastrarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastrarEquipeActionPerformed(evt);
            }
        });
        menEquipe.add(menCadastrarEquipe);

        menListarEquipes.setText("Listar equipes");
        menListarEquipes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListarEquipesActionPerformed(evt);
            }
        });
        menEquipe.add(menListarEquipes);

        barraDeMenu.add(menEquipe);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void menCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastrarClienteActionPerformed
    
        tipo= tela.getTipo();
        
        if (tipo.equals("Administrador")){
            
        CadastroColaborador cadCol = new CadastroColaborador();
        painelPrincipal.add(cadCol, "cadastroColaborador");
        
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "cadastroColaborador");}
    }//GEN-LAST:event_menCadastrarClienteActionPerformed

    private void menListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListarClienteActionPerformed
        
        tipo= tela.getTipo();
        
        if (tipo.equals("Administrador")) {
            
        ListagemColaborador lc = new ListagemColaborador();
        painelPrincipal.add(lc, "listaColaborador"); 
          
        CardLayout cl = (CardLayout) painelPrincipal.getLayout(); 
        cl.show(painelPrincipal, "listaColaborador");}
    }//GEN-LAST:event_menListarClienteActionPerformed

    private void menCadastrarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastrarEquipeActionPerformed
        
        tipo= tela.getTipo();
        
        if (tipo.equals("Administrador")) {
            
        CadastroDeEquipe cadEqu = new CadastroDeEquipe();
        painelPrincipal.add(cadEqu, "cadastroEquipe");
        
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
         cl.show(painelPrincipal, "cadastroEquipe");}
    }//GEN-LAST:event_menCadastrarEquipeActionPerformed

    private void menListarEquipesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListarEquipesActionPerformed
         
        tipo= tela.getTipo();
        
         if (tipo.equals("Administrador" )||tipo.equals("Colaborador")){
        ListagemEquipe lEqu = new ListagemEquipe();
        painelPrincipal.add(lEqu, "listarEquipe");
        
        CardLayout cl = (CardLayout) painelPrincipal.getLayout(); 
        cl.show(painelPrincipal, "listarEquipe");
         }
        
    }//GEN-LAST:event_menListarEquipesActionPerformed

    private void menListarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListarProdutoActionPerformed
        
        tipo= tela.getTipo();
        
        if (tipo.equals("Administrador" )||tipo.equals("Colaborador")) {
            
        CadastroAgenda cAge = new CadastroAgenda();
        painelPrincipal.add(cAge, "cadastroAgenda");
            
        CardLayout cl = (CardLayout) painelPrincipal.getLayout(); 
        cl.show(painelPrincipal, "cadastroAgenda");}
    }//GEN-LAST:event_menListarProdutoActionPerformed

    private void menCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastrarProdutoActionPerformed
       
        tipo= tela.getTipo();
        if (tipo.equals("Administrador")) {
        ListagemAgenda lAge = new ListagemAgenda();
        painelPrincipal.add(lAge, "listarAgenda");
        
        CardLayout cl = (CardLayout) painelPrincipal.getLayout(); 
        cl.show(painelPrincipal, "listarAgenda");
        }
    }//GEN-LAST:event_menCadastrarProdutoActionPerformed

    private void menColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menColaboradorActionPerformed
            
    }//GEN-LAST:event_menColaboradorActionPerformed

    private void menColaboradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menColaboradorMouseClicked
        tipo= tela.getTipo();
        
        if (tipo.equals("")){
        JOptionPane.showMessageDialog(null,"PARA TER ACESSO AO MENU FAÇA O LOGIN!");
        } 
        else if (tipo.equals("Colaborador")){
        JOptionPane.showMessageDialog(null,"ACESSO RESTRITO A ADMINISTRADORES!");
        } 
        
    }//GEN-LAST:event_menColaboradorMouseClicked

    private void menEquipeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menEquipeMouseClicked
        
         tipo= tela.getTipo();
        
        if (tipo.equals("")){
        JOptionPane.showMessageDialog(null,"PARA TER ACESSO AO MENU FAÇA O LOGIN!");
        } 
        else if (tipo.equals("Colaborador")){
        JOptionPane.showMessageDialog(null,"ACESSO RESTRITO A ADMINISTRADORES!");
        } 
        
                                               
        
    }//GEN-LAST:event_menEquipeMouseClicked

    private void menAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menAgendaMouseClicked

        tipo= tela.getTipo();
        
        if (tipo.equals("")){
        JOptionPane.showMessageDialog(null,"PARA TER ACESSO AO MENU FAÇA O LOGIN!");
        } 

    }//GEN-LAST:event_menAgendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistemagestajFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistemagestajFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistemagestajFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistemagestajFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new sistemagestajFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(sistemagestajFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenu menAgenda;
    private javax.swing.JMenuItem menCadastrarCliente;
    private javax.swing.JMenuItem menCadastrarEquipe;
    private javax.swing.JMenuItem menCadastrarProduto;
    private javax.swing.JMenu menColaborador;
    private javax.swing.JMenu menEquipe;
    private javax.swing.JMenuItem menListarCliente;
    private javax.swing.JMenuItem menListarEquipes;
    private javax.swing.JMenuItem menListarProduto;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
